//   Ordt 170915.01 autogenerated file 
//   Input: test.rdl
//   Parms: test.parms
//   Date: Mon Feb 05 18:32:14 CET 2018
//

//
//---------- module simple1_pio
//
module simple1_pio
(
  clk,
  reset,
  h2l_stats_disable_check_0_l0_b0_intr,
  h2l_stats_disable_check_0_l0_b1_intr,
  h2l_stats_disable_check_0_l0_b2_intr,
  h2l_stats_disable_check_1_l0_b0_intr,
  h2l_stats_disable_check_1_l0_b1_intr,
  h2l_stats_disable_check_1_l0_b2_intr,
  h2l_stats_log_address1_value_w,
  h2l_stats_log_address1_value_we,
  h2l_stats_log_address2_value_w,
  h2l_stats_log_address2_value_we,
  h2l_stats_wide_reg_value_w,
  h2l_stats_wide_reg_value_we,
  h2l_rdr_stream_reconf_busy_w,
  h2l_rdr_roll32_counter_reg_count_w,
  h2l_rdr_roll32_counter_reg_count_incr,
  h2l_rdr_roll32_counter_reg_count_we,
  h2l_rdr_sat32_counter_reg_count_w,
  h2l_rdr_sat32_counter_reg_count_incr,
  h2l_rdr_sat32_counter_reg_count_we,
  h2l_rdr_rcnt_sat_log_subch_w,
  h2l_rdr_rcnt_sat_log_subch_we,
  h2l_rdr_rcnt_sat_log_str_w,
  h2l_rdr_rcnt_sat_log_str_we,
  h2l_rdr_rcnt_sat_log_count_w,
  h2l_rdr_rcnt_sat_log_count_we,
  h2d_rdr_cp_fp_wr_r,
  h2d_rdr_cp_fp_wr_ack,
  h2d_rdr_cp_fp_wr_nack,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,

  l2h_stats_disable_check_0_timer_sram_r,
  l2h_stats_disable_check_0_cbuf_fifo_r,
  l2h_stats_disable_check_0_lut_st_r,
  l2h_stats_disable_check_0_l0_b0_r,
  l2h_stats_disable_check_0_l0_b1_r,
  l2h_stats_disable_check_0_l0_b2_r,
  l2h_stats_disable_check_0_l0_b3_r,
  l2h_stats_disable_check_0_intr_o,
  l2h_stats_disable_check_0_halt_o,
  l2h_stats_disable_check_1_timer_sram_r,
  l2h_stats_disable_check_1_cbuf_fifo_r,
  l2h_stats_disable_check_1_lut_st_r,
  l2h_stats_disable_check_1_l0_b0_r,
  l2h_stats_disable_check_1_l0_b1_r,
  l2h_stats_disable_check_1_l0_b2_r,
  l2h_stats_disable_check_1_l0_b3_r,
  l2h_stats_disable_check_1_intr_o,
  l2h_stats_disable_check_1_halt_o,
  l2h_stats_wide_reg_value_r,
  l2h_rdr_reorder_window_ws_enable_r,
  l2h_rdr_reorder_window_set_back_r,
  l2h_rdr_reorder_window_size_r,
  l2h_rdr_stream_reconf_stream_r,
  l2h_rdr_roll32_counter_reg_count_overflow_o,
  l2h_rdr_roll32_counter_reg_count_r,
  l2h_rdr_sat32_counter_reg_count_incrthold_o,
  l2h_rdr_sat32_counter_reg_count_r,
  l2h_rdr_rcnt_sat_log_en_r,
  l2h_rdr_rcnt_sat_log_count_r,
  d2h_rdr_cp_fp_wr_w,
  d2h_rdr_cp_fp_wr_we,
  d2h_rdr_cp_fp_wr_re,
  d2h_rdr_cp_fp_wr_addr,
  l2h_extra_reg_value_r,
  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width );

  //------- inputs
  input    clk;
  input    reset;
  input    h2l_stats_disable_check_0_l0_b0_intr;
  input    h2l_stats_disable_check_0_l0_b1_intr;
  input    h2l_stats_disable_check_0_l0_b2_intr;
  input    h2l_stats_disable_check_1_l0_b0_intr;
  input    h2l_stats_disable_check_1_l0_b1_intr;
  input    h2l_stats_disable_check_1_l0_b2_intr;
  input     [9:0] h2l_stats_log_address1_value_w;
  input    h2l_stats_log_address1_value_we;
  input     [9:0] h2l_stats_log_address2_value_w;
  input    h2l_stats_log_address2_value_we;
  input     [95:0] h2l_stats_wide_reg_value_w;
  input    h2l_stats_wide_reg_value_we;
  input    h2l_rdr_stream_reconf_busy_w;
  input     [3:0] h2l_rdr_roll32_counter_reg_count_w;
  input    h2l_rdr_roll32_counter_reg_count_incr;
  input    h2l_rdr_roll32_counter_reg_count_we;
  input     [3:0] h2l_rdr_sat32_counter_reg_count_w;
  input    h2l_rdr_sat32_counter_reg_count_incr;
  input    h2l_rdr_sat32_counter_reg_count_we;
  input     [4:0] h2l_rdr_rcnt_sat_log_subch_w;
  input    h2l_rdr_rcnt_sat_log_subch_we;
  input     [9:0] h2l_rdr_rcnt_sat_log_str_w;
  input    h2l_rdr_rcnt_sat_log_str_we;
  input     [15:0] h2l_rdr_rcnt_sat_log_count_w;
  input    h2l_rdr_rcnt_sat_log_count_we;
  input     [31:0] h2d_rdr_cp_fp_wr_r;
  input    h2d_rdr_cp_fp_wr_ack;
  input    h2d_rdr_cp_fp_wr_nack;
  input     [127:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;

  //------- outputs
  output    l2h_stats_disable_check_0_timer_sram_r;
  output    l2h_stats_disable_check_0_cbuf_fifo_r;
  output    l2h_stats_disable_check_0_lut_st_r;
  output    l2h_stats_disable_check_0_l0_b0_r;
  output    l2h_stats_disable_check_0_l0_b1_r;
  output    l2h_stats_disable_check_0_l0_b2_r;
  output    l2h_stats_disable_check_0_l0_b3_r;
  output    l2h_stats_disable_check_0_intr_o;
  output    l2h_stats_disable_check_0_halt_o;
  output    l2h_stats_disable_check_1_timer_sram_r;
  output    l2h_stats_disable_check_1_cbuf_fifo_r;
  output    l2h_stats_disable_check_1_lut_st_r;
  output    l2h_stats_disable_check_1_l0_b0_r;
  output    l2h_stats_disable_check_1_l0_b1_r;
  output    l2h_stats_disable_check_1_l0_b2_r;
  output    l2h_stats_disable_check_1_l0_b3_r;
  output    l2h_stats_disable_check_1_intr_o;
  output    l2h_stats_disable_check_1_halt_o;
  output     [95:0] l2h_stats_wide_reg_value_r;
  output    l2h_rdr_reorder_window_ws_enable_r;
  output     [10:0] l2h_rdr_reorder_window_set_back_r;
  output     [10:0] l2h_rdr_reorder_window_size_r;
  output     [9:0] l2h_rdr_stream_reconf_stream_r;
  output    l2h_rdr_roll32_counter_reg_count_overflow_o;
  output     [3:0] l2h_rdr_roll32_counter_reg_count_r;
  output    l2h_rdr_sat32_counter_reg_count_incrthold_o;
  output     [3:0] l2h_rdr_sat32_counter_reg_count_r;
  output    l2h_rdr_rcnt_sat_log_en_r;
  output     [15:0] l2h_rdr_rcnt_sat_log_count_r;
  output     [31:0] d2h_rdr_cp_fp_wr_w;
  output    d2h_rdr_cp_fp_wr_we;
  output    d2h_rdr_cp_fp_wr_re;
  output     [3:2] d2h_rdr_cp_fp_wr_addr;
  output     [31:0] l2h_extra_reg_value_r;
  output     [127:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;


  //------- wire defines
  logic   [31:0] d2l_stats_disable_check_0_w;
  logic  d2l_stats_disable_check_0_we;
  logic  d2l_stats_disable_check_0_re;
  logic   [31:0] d2l_stats_disable_check_1_w;
  logic  d2l_stats_disable_check_1_we;
  logic  d2l_stats_disable_check_1_re;
  logic   [31:0] d2l_stats_features_w;
  logic  d2l_stats_features_we;
  logic  d2l_stats_features_re;
  logic   [31:0] d2l_stats_log_address1_w;
  logic  d2l_stats_log_address1_we;
  logic  d2l_stats_log_address1_re;
  logic   [31:0] d2l_stats_log_address2_w;
  logic  d2l_stats_log_address2_we;
  logic  d2l_stats_log_address2_re;
  logic   [127:0] d2l_stats_wide_reg_w;
  logic  d2l_stats_wide_reg_we;
  logic  d2l_stats_wide_reg_re;
  logic   [31:0] d2l_rdr_reorder_window_w;
  logic  d2l_rdr_reorder_window_we;
  logic  d2l_rdr_reorder_window_re;
  logic   [31:0] d2l_rdr_stream_reconf_w;
  logic  d2l_rdr_stream_reconf_we;
  logic  d2l_rdr_stream_reconf_re;
  logic   [31:0] d2l_rdr_roll32_counter_reg_w;
  logic  d2l_rdr_roll32_counter_reg_we;
  logic  d2l_rdr_roll32_counter_reg_re;
  logic   [31:0] d2l_rdr_sat32_counter_reg_w;
  logic  d2l_rdr_sat32_counter_reg_we;
  logic  d2l_rdr_sat32_counter_reg_re;
  logic   [31:0] d2l_rdr_rcnt_sat_log_w;
  logic  d2l_rdr_rcnt_sat_log_we;
  logic  d2l_rdr_rcnt_sat_log_re;
  logic   [31:0] d2l_extra_reg_w;
  logic  d2l_extra_reg_we;
  logic  d2l_extra_reg_re;
  logic   [31:0] l2d_stats_disable_check_0_r;
  logic   [31:0] l2d_stats_disable_check_1_r;
  logic   [31:0] l2d_stats_features_r;
  logic   [31:0] l2d_stats_log_address1_r;
  logic   [31:0] l2d_stats_log_address2_r;
  logic   [127:0] l2d_stats_wide_reg_r;
  logic   [31:0] l2d_rdr_reorder_window_r;
  logic   [31:0] l2d_rdr_stream_reconf_r;
  logic   [31:0] l2d_rdr_roll32_counter_reg_r;
  logic   [31:0] l2d_rdr_sat32_counter_reg_r;
  logic   [31:0] l2d_rdr_rcnt_sat_log_r;
  logic   [31:0] l2d_extra_reg_r;
  
  
  simple1_jrdl_decode pio_decode ( .* );
    
  simple1_jrdl_logic pio_logic ( .* );
    
endmodule

