//   Ordt 170915.01 autogenerated file 
//   Input: test.rdl
//   Parms: test.parms
//   Date: Mon Feb 05 18:32:14 CET 2018
//

//
//---------- module simple1_jrdl_decode
//
module simple1_jrdl_decode
(
  clk,
  reset,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,
  l2d_stats_disable_check_0_r,
  l2d_stats_disable_check_1_r,
  l2d_stats_features_r,
  l2d_stats_log_address1_r,
  l2d_stats_log_address2_r,
  l2d_stats_wide_reg_r,
  l2d_rdr_reorder_window_r,
  l2d_rdr_stream_reconf_r,
  l2d_rdr_roll32_counter_reg_r,
  l2d_rdr_sat32_counter_reg_r,
  l2d_rdr_rcnt_sat_log_r,
  l2d_extra_reg_r,
  h2d_rdr_cp_fp_wr_r,
  h2d_rdr_cp_fp_wr_ack,
  h2d_rdr_cp_fp_wr_nack,

  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width,
  d2l_stats_disable_check_0_w,
  d2l_stats_disable_check_0_we,
  d2l_stats_disable_check_0_re,
  d2l_stats_disable_check_1_w,
  d2l_stats_disable_check_1_we,
  d2l_stats_disable_check_1_re,
  d2l_stats_features_w,
  d2l_stats_features_we,
  d2l_stats_features_re,
  d2l_stats_log_address1_w,
  d2l_stats_log_address1_we,
  d2l_stats_log_address1_re,
  d2l_stats_log_address2_w,
  d2l_stats_log_address2_we,
  d2l_stats_log_address2_re,
  d2l_stats_wide_reg_w,
  d2l_stats_wide_reg_we,
  d2l_stats_wide_reg_re,
  d2l_rdr_reorder_window_w,
  d2l_rdr_reorder_window_we,
  d2l_rdr_reorder_window_re,
  d2l_rdr_stream_reconf_w,
  d2l_rdr_stream_reconf_we,
  d2l_rdr_stream_reconf_re,
  d2l_rdr_roll32_counter_reg_w,
  d2l_rdr_roll32_counter_reg_we,
  d2l_rdr_roll32_counter_reg_re,
  d2l_rdr_sat32_counter_reg_w,
  d2l_rdr_sat32_counter_reg_we,
  d2l_rdr_sat32_counter_reg_re,
  d2l_rdr_rcnt_sat_log_w,
  d2l_rdr_rcnt_sat_log_we,
  d2l_rdr_rcnt_sat_log_re,
  d2l_extra_reg_w,
  d2l_extra_reg_we,
  d2l_extra_reg_re,
  d2h_rdr_cp_fp_wr_w,
  d2h_rdr_cp_fp_wr_we,
  d2h_rdr_cp_fp_wr_re,
  d2h_rdr_cp_fp_wr_addr );

  //------- inputs
  input    clk;
  input    reset;
  input     [127:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;
  input     [31:0] l2d_stats_disable_check_0_r;
  input     [31:0] l2d_stats_disable_check_1_r;
  input     [31:0] l2d_stats_features_r;
  input     [31:0] l2d_stats_log_address1_r;
  input     [31:0] l2d_stats_log_address2_r;
  input     [127:0] l2d_stats_wide_reg_r;
  input     [31:0] l2d_rdr_reorder_window_r;
  input     [31:0] l2d_rdr_stream_reconf_r;
  input     [31:0] l2d_rdr_roll32_counter_reg_r;
  input     [31:0] l2d_rdr_sat32_counter_reg_r;
  input     [31:0] l2d_rdr_rcnt_sat_log_r;
  input     [31:0] l2d_extra_reg_r;
  input     [31:0] h2d_rdr_cp_fp_wr_r;
  input    h2d_rdr_cp_fp_wr_ack;
  input    h2d_rdr_cp_fp_wr_nack;

  //------- outputs
  output     [127:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;
  output     [31:0] d2l_stats_disable_check_0_w;
  output    d2l_stats_disable_check_0_we;
  output    d2l_stats_disable_check_0_re;
  output     [31:0] d2l_stats_disable_check_1_w;
  output    d2l_stats_disable_check_1_we;
  output    d2l_stats_disable_check_1_re;
  output     [31:0] d2l_stats_features_w;
  output    d2l_stats_features_we;
  output    d2l_stats_features_re;
  output     [31:0] d2l_stats_log_address1_w;
  output    d2l_stats_log_address1_we;
  output    d2l_stats_log_address1_re;
  output     [31:0] d2l_stats_log_address2_w;
  output    d2l_stats_log_address2_we;
  output    d2l_stats_log_address2_re;
  output     [127:0] d2l_stats_wide_reg_w;
  output    d2l_stats_wide_reg_we;
  output    d2l_stats_wide_reg_re;
  output     [31:0] d2l_rdr_reorder_window_w;
  output    d2l_rdr_reorder_window_we;
  output    d2l_rdr_reorder_window_re;
  output     [31:0] d2l_rdr_stream_reconf_w;
  output    d2l_rdr_stream_reconf_we;
  output    d2l_rdr_stream_reconf_re;
  output     [31:0] d2l_rdr_roll32_counter_reg_w;
  output    d2l_rdr_roll32_counter_reg_we;
  output    d2l_rdr_roll32_counter_reg_re;
  output     [31:0] d2l_rdr_sat32_counter_reg_w;
  output    d2l_rdr_sat32_counter_reg_we;
  output    d2l_rdr_sat32_counter_reg_re;
  output     [31:0] d2l_rdr_rcnt_sat_log_w;
  output    d2l_rdr_rcnt_sat_log_we;
  output    d2l_rdr_rcnt_sat_log_re;
  output     [31:0] d2l_extra_reg_w;
  output    d2l_extra_reg_we;
  output    d2l_extra_reg_re;
  output     [31:0] d2h_rdr_cp_fp_wr_w;
  output    d2h_rdr_cp_fp_wr_we;
  output    d2h_rdr_cp_fp_wr_re;
  output     [3:2] d2h_rdr_cp_fp_wr_addr;


  //------- wire defines
  logic   [31:0] h2d_rdr_cp_fp_wr_r_ex;
  logic  h2d_rdr_cp_fp_wr_ack_ex;
  logic  h2d_rdr_cp_fp_wr_nack_ex;
  logic   [127:0] pio_dec_write_data;
  logic   [14:2] pio_dec_address;
  logic  pio_dec_read;
  logic  pio_dec_write;
  logic   [39:0] block_sel_addr;
  logic  block_sel;
  logic  leaf_dec_valid_active;
  logic  leaf_dec_wr_dvld_active;
  logic   [1:0] pio_dec_trans_size;
  logic  dec_leaf_retry_atomic_next;
  
  //------- reg defines
  logic   [31:0] d2l_stats_disable_check_0_w;
  logic  d2l_stats_disable_check_0_we;
  logic  d2l_stats_disable_check_0_re;
  logic   [31:0] d2l_stats_disable_check_1_w;
  logic  d2l_stats_disable_check_1_we;
  logic  d2l_stats_disable_check_1_re;
  logic   [31:0] d2l_stats_features_w;
  logic  d2l_stats_features_we;
  logic  d2l_stats_features_re;
  logic   [31:0] d2l_stats_log_address1_w;
  logic  d2l_stats_log_address1_we;
  logic  d2l_stats_log_address1_re;
  logic   [31:0] d2l_stats_log_address2_w;
  logic  d2l_stats_log_address2_we;
  logic  d2l_stats_log_address2_re;
  logic   [127:0] d2l_stats_wide_reg_w;
  logic  d2l_stats_wide_reg_we;
  logic  d2l_stats_wide_reg_re;
  logic   [31:0] d2l_rdr_reorder_window_w;
  logic  d2l_rdr_reorder_window_we;
  logic  d2l_rdr_reorder_window_re;
  logic   [31:0] d2l_rdr_stream_reconf_w;
  logic  d2l_rdr_stream_reconf_we;
  logic  d2l_rdr_stream_reconf_re;
  logic   [31:0] d2h_rdr_cp_fp_wr_w_ex;
  logic  d2h_rdr_cp_fp_wr_we_ex;
  logic  d2h_rdr_cp_fp_wr_re_ex;
  logic   [31:0] d2h_rdr_cp_fp_wr_w_next;
  logic  d2h_rdr_cp_fp_wr_we_next;
  logic  d2h_rdr_cp_fp_wr_re_next;
  logic   [3:2] d2h_rdr_cp_fp_wr_addr_ex;
  logic   [3:2] d2h_rdr_cp_fp_wr_addr_next;
  logic   [31:0] d2l_rdr_roll32_counter_reg_w;
  logic  d2l_rdr_roll32_counter_reg_we;
  logic  d2l_rdr_roll32_counter_reg_re;
  logic   [31:0] d2l_rdr_sat32_counter_reg_w;
  logic  d2l_rdr_sat32_counter_reg_we;
  logic  d2l_rdr_sat32_counter_reg_re;
  logic   [31:0] d2l_rdr_rcnt_sat_log_w;
  logic  d2l_rdr_rcnt_sat_log_we;
  logic  d2l_rdr_rcnt_sat_log_re;
  logic   [31:0] d2l_extra_reg_w;
  logic  d2l_extra_reg_we;
  logic  d2l_extra_reg_re;
  logic  leaf_dec_valid_hld1;
  logic  leaf_dec_valid_hld1_next;
  logic  leaf_dec_wr_dvld_hld1;
  logic  leaf_dec_wr_dvld_hld1_next;
  logic  dec_leaf_retry_atomic;
  logic  pio_write_active;
  logic  pio_read_active;
  logic   [14:2] pio_dec_address_d1;
  logic   [127:0] pio_dec_write_data_d1;
  logic   [1:0] pio_dec_trans_size_d1;
  logic   [1:0] dec_pio_trans_size;
  logic   [1:0] reg_width;
  logic   [127:0] dec_pio_read_data;
  logic   [127:0] dec_pio_read_data_d1;
  logic  dec_pio_ack;
  logic  dec_pio_nack;
  logic  dec_pio_ack_next;
  logic  dec_pio_nack_next;
  logic  pio_internal_ack;
  logic  pio_internal_nack;
  logic  pio_external_ack;
  logic  pio_external_nack;
  logic  pio_external_ack_next;
  logic  pio_external_nack_next;
  logic  pio_no_acks;
  logic  pio_activate_write;
  logic  pio_activate_read;
  logic   [127:0] dec_pio_read_data_next;
  logic  external_transaction_active;
  
  
  //------- assigns
  assign  d2h_rdr_cp_fp_wr_we = d2h_rdr_cp_fp_wr_we_ex;
  assign  d2h_rdr_cp_fp_wr_w = d2h_rdr_cp_fp_wr_w_ex;
  assign  d2h_rdr_cp_fp_wr_re = d2h_rdr_cp_fp_wr_re_ex;
  assign  h2d_rdr_cp_fp_wr_r_ex = h2d_rdr_cp_fp_wr_r;
  assign  h2d_rdr_cp_fp_wr_ack_ex = h2d_rdr_cp_fp_wr_ack;
  assign  h2d_rdr_cp_fp_wr_nack_ex = h2d_rdr_cp_fp_wr_nack;
  assign  d2h_rdr_cp_fp_wr_addr = d2h_rdr_cp_fp_wr_addr_ex;
  assign  pio_dec_write_data = leaf_dec_wr_data;
  assign  dec_leaf_rd_data = dec_pio_read_data;
  assign  dec_leaf_ack = dec_pio_ack;
  assign  dec_leaf_nack = dec_pio_nack;
  assign  pio_dec_address = leaf_dec_addr [14:2] ;
  assign  block_sel_addr = 40'h0;
  assign  block_sel = leaf_dec_block_sel;
  assign  leaf_dec_wr_dvld_active = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
  assign  leaf_dec_valid_active = leaf_dec_valid | leaf_dec_valid_hld1;
  assign  dec_leaf_accept = leaf_dec_valid & block_sel;
  assign  dec_leaf_reject = leaf_dec_valid & ~block_sel;
  assign  pio_dec_read = block_sel & leaf_dec_valid_active & (leaf_dec_cycle == 2'b10);
  assign  pio_dec_write = block_sel & leaf_dec_wr_dvld_active & (leaf_dec_cycle[1] == 1'b0);
  assign  pio_dec_trans_size = leaf_dec_wr_width [1:0] ;
  assign  dec_leaf_data_width [2]  = 0;
  assign  dec_leaf_data_width [1:0]  = dec_pio_trans_size;
  assign  dec_leaf_retry_atomic_next = block_sel & leaf_dec_wr_dvld_active & (leaf_dec_cycle == 2'b00) & (leaf_dec_wr_width [1:0]  < reg_width);
  
  //------- combinatorial assigns for pio read data
  always_comb begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end
  
  //------- reg assigns for pio read data
  always_ff @ (posedge clk) begin
    if (reset) begin
      dec_pio_read_data_d1 <= #1  128'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end
  
  //------- reg assigns for pio i/f
  always_ff @ (posedge clk) begin
    if (reset) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
      dec_pio_trans_size <= #1 2'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
      pio_dec_address_d1 <= #1   pio_dec_address;
      pio_dec_write_data_d1 <= #1  pio_dec_write_data;
      pio_dec_trans_size_d1 <= #1  pio_dec_trans_size;
      dec_pio_trans_size <= #1 reg_width;
    end
  end
  
  //------- reg assigns for external i/f
  always_ff @ (posedge clk) begin
    if (reset) begin
      d2h_rdr_cp_fp_wr_we_ex <= #1  1'b0;
      d2h_rdr_cp_fp_wr_re_ex <= #1  1'b0;
    end
    else begin
      d2h_rdr_cp_fp_wr_w_ex <= #1  d2h_rdr_cp_fp_wr_w_next;
      d2h_rdr_cp_fp_wr_we_ex <= #1  d2h_rdr_cp_fp_wr_we_next & ~h2d_rdr_cp_fp_wr_ack_ex & ~h2d_rdr_cp_fp_wr_nack_ex;
      d2h_rdr_cp_fp_wr_re_ex <= #1  d2h_rdr_cp_fp_wr_re_next & ~h2d_rdr_cp_fp_wr_ack_ex & ~h2d_rdr_cp_fp_wr_nack_ex;
      d2h_rdr_cp_fp_wr_addr_ex <= #1  d2h_rdr_cp_fp_wr_addr_next;
    end
  end
  
  //------- combinatorial assigns for leaf i/f
  always_comb begin
    leaf_dec_valid_hld1_next = leaf_dec_valid | leaf_dec_valid_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next) leaf_dec_valid_hld1_next = 1'b0;
    leaf_dec_wr_dvld_hld1_next = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next | leaf_dec_valid) leaf_dec_wr_dvld_hld1_next = 1'b0;
  end
  
  //------- reg assigns for leaf i/f
  always_ff @ (posedge clk) begin
    if (reset) begin
      leaf_dec_valid_hld1 <= #1  1'b0;
      leaf_dec_wr_dvld_hld1 <= #1  1'b0;
      dec_leaf_retry_atomic <= #1  1'b0;
    end
    else begin
      leaf_dec_valid_hld1 <= #1 leaf_dec_valid_hld1_next;
      leaf_dec_wr_dvld_hld1 <= #1 leaf_dec_wr_dvld_hld1_next;
      dec_leaf_retry_atomic <= #1 dec_leaf_retry_atomic_next;
    end
  end
  
  //------- combinatorial assigns for pio ack/nack
  always_comb begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end
  
  //------- reg assigns for pio ack/nack
  always_ff @ (posedge clk) begin
    if (reset) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end
  
  
  //------- address decode
  always_comb begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 128'b0;
    reg_width = 2'd0;
    
    d2l_stats_disable_check_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_stats_disable_check_0_we = 1'b0;
    d2l_stats_disable_check_0_re = 1'b0;
    d2l_stats_disable_check_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_stats_disable_check_1_we = 1'b0;
    d2l_stats_disable_check_1_re = 1'b0;
    d2l_stats_features_w = pio_dec_write_data_d1  [31:0] ;
    d2l_stats_features_we = 1'b0;
    d2l_stats_features_re = 1'b0;
    d2l_stats_log_address1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_stats_log_address1_we = 1'b0;
    d2l_stats_log_address1_re = 1'b0;
    d2l_stats_log_address2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_stats_log_address2_we = 1'b0;
    d2l_stats_log_address2_re = 1'b0;
    d2l_stats_wide_reg_w = pio_dec_write_data_d1  [127:0] ;
    d2l_stats_wide_reg_we = 1'b0;
    d2l_stats_wide_reg_re = 1'b0;
    d2l_rdr_reorder_window_w = pio_dec_write_data_d1  [31:0] ;
    d2l_rdr_reorder_window_we = 1'b0;
    d2l_rdr_reorder_window_re = 1'b0;
    d2l_rdr_stream_reconf_w = pio_dec_write_data_d1  [31:0] ;
    d2l_rdr_stream_reconf_we = 1'b0;
    d2l_rdr_stream_reconf_re = 1'b0;
    d2h_rdr_cp_fp_wr_w_next = pio_dec_write_data_d1 [31:0] ;
    d2h_rdr_cp_fp_wr_we_next = 1'b0;
    d2h_rdr_cp_fp_wr_re_next = 1'b0;
    d2h_rdr_cp_fp_wr_addr_next = pio_dec_address_d1  [3:2] ;
    d2l_rdr_roll32_counter_reg_w = pio_dec_write_data_d1  [31:0] ;
    d2l_rdr_roll32_counter_reg_we = 1'b0;
    d2l_rdr_roll32_counter_reg_re = 1'b0;
    d2l_rdr_sat32_counter_reg_w = pio_dec_write_data_d1  [31:0] ;
    d2l_rdr_sat32_counter_reg_we = 1'b0;
    d2l_rdr_sat32_counter_reg_re = 1'b0;
    d2l_rdr_rcnt_sat_log_w = pio_dec_write_data_d1  [31:0] ;
    d2l_rdr_rcnt_sat_log_we = 1'b0;
    d2l_rdr_rcnt_sat_log_re = 1'b0;
    d2l_extra_reg_w = pio_dec_write_data_d1  [31:0] ;
    d2l_extra_reg_we = 1'b0;
    d2l_extra_reg_re = 1'b0;
    
    casez(pio_dec_address_d1)
    //  Register: stats.disable_check_0     Address: 0x1000     External: false
    13'b0010000000000:
      begin
        d2l_stats_disable_check_0_we = pio_write_active & ~dec_pio_ack;
        d2l_stats_disable_check_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_stats_disable_check_0_r;
      end
    //  Register: stats.disable_check_1     Address: 0x1080     External: false
    13'b0010000100000:
      begin
        d2l_stats_disable_check_1_we = pio_write_active & ~dec_pio_ack;
        d2l_stats_disable_check_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_stats_disable_check_1_r;
      end
    //  Register: stats.features     Address: 0x1100     External: false
    13'b0010001000000:
      begin
        d2l_stats_features_we = pio_write_active & ~dec_pio_ack;
        d2l_stats_features_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_stats_features_r;
      end
    //  Register: stats.log_address1     Address: 0x1104     External: false
    13'b0010001000001:
      begin
        d2l_stats_log_address1_we = pio_write_active & ~dec_pio_ack;
        d2l_stats_log_address1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_stats_log_address1_r;
      end
    //  Register: stats.log_address2     Address: 0x1110     External: false
    13'b0010001000100:
      begin
        d2l_stats_log_address2_we = pio_write_active & ~dec_pio_ack;
        d2l_stats_log_address2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_stats_log_address2_r;
      end
    //  Register: stats.wide_reg     Address: 0x1120     External: false
    13'b00100010010??:
      begin
        reg_width = 2'd3;
        d2l_stats_wide_reg_we = pio_write_active & ~dec_pio_ack & (pio_dec_trans_size_d1 >= reg_width);
        d2l_stats_wide_reg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [127:0]  = l2d_stats_wide_reg_r;
      end
    //  Register: rdr.reorder_window     Address: 0x4000     External: false
    13'b1000000000000:
      begin
        d2l_rdr_reorder_window_we = pio_write_active & ~dec_pio_ack;
        d2l_rdr_reorder_window_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_rdr_reorder_window_r;
      end
    //  Register: rdr.stream_reconf     Address: 0x4004     External: false
    13'b1000000000001:
      begin
        d2l_rdr_stream_reconf_we = pio_write_active & ~dec_pio_ack;
        d2l_rdr_stream_reconf_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_rdr_stream_reconf_r;
      end
    //  Register: rdr.cp_fp_wr     Address: 0x61c0     External: true
    13'b11000011100??:
      begin
        d2h_rdr_cp_fp_wr_we_next = pio_write_active & ~(pio_external_ack | pio_external_nack);
        pio_external_ack_next = h2d_rdr_cp_fp_wr_ack_ex;
        external_transaction_active = pio_read_active | pio_write_active;
        d2h_rdr_cp_fp_wr_re_next = pio_read_active & ~(pio_external_ack | pio_external_nack);
        pio_external_nack_next = h2d_rdr_cp_fp_wr_nack_ex;
        dec_pio_read_data_next  [31:0]  = h2d_rdr_cp_fp_wr_r_ex;
      end
    //  Register: rdr.roll32_counter_reg     Address: 0x61d0     External: false
    13'b1100001110100:
      begin
        d2l_rdr_roll32_counter_reg_we = pio_write_active & ~dec_pio_ack;
        d2l_rdr_roll32_counter_reg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_rdr_roll32_counter_reg_r;
      end
    //  Register: rdr.sat32_counter_reg     Address: 0x61d4     External: false
    13'b1100001110101:
      begin
        d2l_rdr_sat32_counter_reg_we = pio_write_active & ~dec_pio_ack;
        d2l_rdr_sat32_counter_reg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_rdr_sat32_counter_reg_r;
      end
    //  Register: rdr.rcnt_sat_log     Address: 0x61d8     External: false
    13'b1100001110110:
      begin
        d2l_rdr_rcnt_sat_log_we = pio_write_active & ~dec_pio_ack;
        d2l_rdr_rcnt_sat_log_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_rdr_rcnt_sat_log_r;
      end
    //  Register: extra_reg     Address: 0x61dc     External: false
    13'b1100001110111:
      begin
        d2l_extra_reg_we = pio_write_active & ~dec_pio_ack;
        d2l_extra_reg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_extra_reg_r;
      end
    endcase
  end
  
endmodule

